title:            André Barbosa
description:      "Just another blog about random things..."
logo:             
disqus_shortname: andremanuelbarbosa
default_bg:       pomegranates.jpg
search:           true
share:            true
readtime:         false
triangleheader:   true
animated_fins:    true
fin_color:        "255,255,255"
url:              http://www.andremanuelbarbosa.com
baseurl:          

owner:
  name:           André Barbosa
  avatar:         andremanuelbarbosa.jpg
  email:          andremanuelbarbosa@gmail.com
  description:    Senior PS Engineer @ Jive Software
  twitter:        andremanbarbosa
  facebook:       
  github:         andremanuelbarbosa
  stackexchange:  https://stackexchange.com/users/1091174/andr%C3%A9-barbosa
  linkedin:       http://www.linkedin.com/in/andremanuelbarbosa
  instagram:      andremanuelbarbosa
  flickr:         
  tumblr:         
  hmfaysalsocial: 
  google_plus:    http://plus.google.com/108526886375667222281

google_analytics: UA-1018627-19
google_verify:    
bing_verify:      

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags

timezone:    Europe/London
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

syntax_highlighter_opts:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://andremanuelbarbosa.github.io/'
  relativeLinks: 'http://andremanuelbarbosa.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "type"
        field:
          element: "select"
          label: "Select Post Type"
          placeholder: "Choose your type"
          options:
            - name: "Standard"
              value: 
            - name: "Quote"
              value: quote
            - name: "Status"
              value: status
            - name: "Photo"
              value: photo
            - name: "Video"
              value: video
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Web-Development"
              value: webdevelopment
            - name: "Interesting"
              value: interesting
            - name: "Status"
              value: status
            - name: "Quotes"
              value: quotes
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "imagecredit"
        field:
          element: "text"
          label: "Image Credit"
          placeholder: "some guy"
      - name: "imagecreditlink"
        field:
          element: "text"
          label: "Credit link for the image"
          placeholder: "http://somewebsite.com"
      - name: "video"
        field:
          element: "text"
          label: "Insert Youtube Link"
          placeholder: "http://youtube.com/somevideo"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
